const foodToCuisine = {
  "Italian": ["pizza", "pasta", "risotto", "gelato", "tiramisu", "lasagna", "carbonara", "bruschetta", "minestrone", "gnocchi", "panna cotta", "cannoli", "osso buco", "caprese salad", "spaghetti aglio e olio", "calzone", "affogato", "cioppino", "limoncello"],
  "Chinese": ["dumplings", "spring rolls", "fried rice", "kung pao chicken", "sweet and sour pork", "chow mein", "hot and sour soup", "peking duck", "dim sum", "mapo tofu", "general tso's chicken", "mongolian beef", "orange chicken", "egg foo young", "crab rangoon", "sesame chicken", "baozi", "congee", "dan dan noodles"],
  "Mexican": ["tacos", "burritos", "quesadillas", "guacamole", "churros", "enchiladas", "tamales", "salsa", "fajitas", "nachos", "ceviche", "mole", "tostadas", "flautas", "horchata", "elote", "pambazo", "sopes", "pozole", "carnitas"],
  "Japanese": ["sushi", "ramen", "tempura", "miso soup", "teriyaki", "sashimi", "udon", "onigiri", "tonkatsu", "yakitori", "okonomiyaki", "takoyaki", "nigiri", "matcha", "kaiseki", "sukiyaki", "donburi", "soba", "katsu curry", "gyudon"],
  "Indian": ["butter chicken", "biryani", "samosas", "naan", "tandoori chicken", "dal", "paneer", "rogan josh", "chai", "jalebi", "vindaloo", "masala dosa", "papdi chaat", "pakora", "pav bhaji", "gulab jamun", "lassi", "kulfi", "kheer", "rasgulla"],
  "French": ["croissant", "baguette", "ratatouille", "crepes", "escargot", "coq au vin", "bouillabaisse", "quiche", "macarons", "soufflé", "foie gras", "cassoulet", "croque monsieur", "éclair", "brie", "profiteroles", "niçoise salad", "tarte tatin", "petit fours", "boeuf bourguignon"],
  "American": ["hamburger", "hot dog", "fried chicken", "apple pie", "mac and cheese", "barbecue ribs", "clam chowder", "meatloaf", "cornbread", "chili", "cheeseburger", "lobster roll", "key lime pie", "corn dogs", "mashed potatoes", "pulled pork sandwich", "philly cheesesteak", "peanut butter and jelly sandwich", "buffalo wings", "grits"],
  "Greek": ["gyros", "souvlaki", "moussaka", "tzatziki", "spanakopita", "baklava", "dolma", "feta cheese", "greek salad", "horiatiki", "tiropita", "loukoumades", "pastitsio", "saganaki", "kleftiko", "taramasalata", "avgolemono", "halva", "melitzanosalata", "koulouri"],
  "Thai": ["pad thai", "green curry", "tom yum soup", "som tam", "mango sticky rice", "red curry", "massaman curry", "satay", "larb", "kai yang", "khao soi", "panang curry", "thai tea", "pad see ew", "thai basil chicken", "papaya salad", "sticky rice", "miang kham", "pla rad prik", "thai coconut soup"],
  "Spanish": ["paella", "tapas", "gazpacho", "churros", "tortilla española", "patatas bravas", "jamón ibérico", "croquetas", "empanadas", "flan", "sangria", "pisto", "escabeche", "fabada asturiana", "alioli", "coca", "pulpo a la gallega", "salmorejo", "turrón", "bacalao al pil pil"],
  "Korean": ["kimchi", "bibimbap", "bulgogi", "tteokbokki", "samgyeopsal", "japchae", "pajeon", "galbi", "soondubu jjigae", "kimchi jjigae", "mandu", "kimchi fried rice", "bossam", "jajangmyeon", "banchan", "yukgaejang", "tteokguk", "sundubu", "dakgalbi", "jeyuk bokkeum"],
  "Vietnamese": ["pho", "banh mi", "spring rolls", "bun cha", "banh xeo", "ca phe sua da", "com tam", "bun rieu", "goi cuon", "cha gio", "bun bo hue", "mi quang", "banh canh", "pho ga", "hu tieu", "goi du du", "ca nuong", "thit kho", "banh cuon", "bo la lot"],
  "Middle Eastern": ["hummus", "falafel", "shawarma", "tabbouleh", "baba ghanoush", "kebabs", "fattoush", "baklava", "labneh", "manakish", "kibbeh", "musakhan", "kanafeh", "kushari", "warbat", "shakshuka", "mahshi", "ful medames", "zaatar", "muhammara"],
  "Brazilian": ["feijoada", "pão de queijo", "brigadeiro", "moqueca", "acarajé", "coxinha", "farofa", "empadão", "tapioca", "caipirinha", "pastel", "churrasco", "picanha", "tutu de feijão", "coxinha", "quindim", "beijinho", "cuscuz", "vatapá", "pudim"],
  "Turkish": ["kebabs", "köfte", "lahmacun", "pide", "börek", "mantı", "çiğ köfte", "tavuk göğsü", "baklava", "lokum", "sarma", "kısır", "pastırma", "simit", "menemen", "tahini", "çöp şiş", "midye dolma", "şakşuka", "çiğ köfte"],
  "Ethiopian": ["injera", "doro wat", "kitfo", "tibs", "shiro", "ful", "gomen", "tej", "firfir", "berbere", "ayib", "kik alicha", "doro tibs", "fitfit", "siga wat", "misir wat", "atikilt wat", "gored gored", "genfo", "kocho"],
  "Caribbean": ["jerk chicken", "ackee and saltfish", "plantains", "curry goat", "rice and peas", "roti", "callaloo", "oxtail stew", "conch fritters", "sorrel", "griot", "cassava cake", "doubles", "rundown", "pelau", "coconut shrimp", "bajan flying fish", "jamaican patty", "black cake", "fish escovitch"],
  "Moroccan": ["couscous", "tagine", "bastilla", "pastilla", "harira", "briouat", "kefta", "zaalouk", "ras el hanout", "chermoula", "msemen", "rfissa", "maakouda", "taktouka", "mint tea", "mlawi", "b'stilla", "makrout", "seffa", "mrouzia"]
}

export { foodToCuisine }